### ISSUE TITLE
求大佬开发个station m2的固件吧

### ISSUE THREAD

**Issue by Ma-Junhan** [DHDAXCW/Station_P2-M2#1]
如题，跪求……

**Comment by DHDAXCW** [comment]
emmm...

**Comment by DHDAXCW** [comment]
明天发布。莫急。。。

**Comment by Ma-Junhan** [comment]
非常感谢！！作为小白按照官方wiki尝试了一下自编固件，有N多搞不通的地方，比如make menuconfig之后编出来的还是没改过的东西……都快哭了……

**Comment by Ma-Junhan** [comment]
等了这么久……我还是把m2卖掉吧……

**Comment by Javier-Huang** [comment]
> 非常感谢！！作为小白按照官方wiki尝试了一下自编固件，有N多搞不通的地方，比如make menuconfig之后编出来的还是没改过的东西……都快哭了……

因为使用的是configs/rk356x_config，每次make menuconfig之后，需要保存配置make savedefconfig，并用defconfig覆盖configs/rk356x_config

**Comment by DHDAXCW** [comment]
就是哇

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/Station_P2-M2/releases/tag/2021.12.13  固件在这里哦

**Comment by Ma-Junhan** [comment]
！！！终于来了！感谢……
